######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 6 14:18:49 2008
######################################################################

CONFIG += release
TEMPLATE = app
TARGET = ../update
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../showMessage.h mainWindow.h
SOURCES += update.cpp ../showMessage.cpp mainWindow.cpp

TRANSLATIONS += update_bg.ts
